Repository sendgrid/php-http-client, pull requests merged in 2018-03, with the labels that each got.

#87 Fix #81: Stop using insecure option by default
  lib/Client.php
Labels: difficulty: easy, status: ready for deploy, type: security

#86 add phpdoc for send method
  lib/Client.php
Labels: difficulty: easy, status: code review request, type: docs update

#85 Updated the PHP Version details.
  .github/ISSUE_TEMPLATE
Labels: difficulty: easy, status: code review request, type: docs update

#89 Fix #88: Missing Function
  lib/Client.php
Labels: difficulty: easy, status: code review request, type: bug

#91 Fix #12, union operator
  lib/Client.php
Labels: difficulty: easy, status: code review request, type: bug

#93 Don't overwrite headers set from upstream dependencies
  lib/Client.php
Labels: difficulty: easy, status: code review request, type: bug

#92 PSR2 fixes
  lib/Client.php
  lib/Response.php
  test/unit/FilesExistTest.php
  test/unit/LicenceYearTest.php
Labels: difficulty: easy, status: code review request, type: community enhancement

#96 Fix Constructor Signature
  lib/Client.php
  test/unit/ClientTest.php
Labels: difficulty: easy, status: code review request, status: work in progress, type: bug

#95 CreateCurlOptions method regression tests
  lib/Client.php
  lib/Response.php
  test/unit/ClientTest.php
  test/unit/LicenceYearTest.php
  test/unit/ResponseTest.php
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement
